# These are supported funding model platforms

# github: [nu11secur1ty]
patreon: nu11secur1ty
custom: ["https://pypi.org/project/shtaklatanemoosaizmuknesh/", pypi.org]
custom: ["https://pypi.org/user/nu11secur1ty/"]
